use std::{
    fmt::Display,
    io::ErrorKind,
    net::{SocketAddr, ToSocketAddrs},
    path::Path,
    pin::pin,
    sync::{
        Arc, Mutex,
        atomic::{AtomicBool, Ordering},
    },
    task::{Context, Waker},
    time::Duration,
};

use clap::{Parser, Subcommand};
use futures::{StreamExt, stream::BoxStream};
use iroh::{
    Endpoint, EndpointAddr, EndpointId, SecretKey, TransportAddr, Watcher,
    address_lookup::{self, AddressLookup, PkarrPublisher, PkarrPublisherBuilder, PkarrResolver},
    endpoint_info::EndpointData,
};
use serde::{Deserialize, Serialize};
use tokio::{
    io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt, copy_bidirectional},
    net::{TcpListener, TcpSocket},
    spawn,
    sync::oneshot,
    task::{AbortHandle, JoinHandle},
    time::sleep,
};

const PACKAGE_NAME: &str = env!("CARGO_PKG_NAME");
const CONFIG_FILE: &str = "config.toml";
const DEFAULT_ALPN: &str = "ServerP2Pv0";
const TICKET_PREFIX: &str = "sp2p";
const HANDSHAKE_TCP_REQUEST: &[u8] = b"sp2pPingTCP";
const HANDSHAKE_TCP_RESPONSE: &[u8] = b"sp2pPongTCP";
const HANDSHAKE_UDP_REQUEST: &[u8] = b"sp2pPingUDP";
const HANDSHAKE_UDP_RESPONSE: &[u8] = b"sp2pPongUDP";
const TOML_TEMPLATE: &str = "\
    # ******************************************************************************************************\n\
    # This file was automatically generated by `server_share prepare` command.\n\
    # Do not share the content of this file with other users, it can be used to impersonate your address.\n\
    # ******************************************************************************************************\n\n\
    [config]\n\
    # Secret key that can be used to generate 'serve' tickets\n\
    secret_key = \"%%SECRET_KEY%%\"\n\n\
    # Listener secret key that can be used to generate 'listen' tickets that other serving party may\n\
    # add to 'allow_list', you can specify same key as 'secret_key' by putting here \"secret_key\" or \"same\"\n\
    # no/empty value means that key will be generated every time\n\
    listen_secret_key = \"\"\n\n\
    # List of allowed listener tickets that can connect to you when using `serve` command\n\
    # e.g allow_list = [\"sp2p4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS\"]\n\
    # no/empty value means to allow all listeners\n\
    allow_list = []
";
const PATTERN_SECRET_KEY: &str = "%%SECRET_KEY%%";
const SECRET_TOML_REFS: &[&str] = &["secret_key", "same"];

/// Share your local server without public IP address
#[derive(Parser, Debug)]
pub struct Args {
    #[clap(subcommand)]
    pub command: Commands,
}

#[derive(Subcommand, Debug)]
pub enum Commands {
    /// Listen on connections to local port and forward them to remote shared server.
    Listen(ListenArgs),

    /// Creates a server and prints a node address that can be used to connect.
    Serve(ServeArgs),

    /// Generates a server config.toml file in current directory.
    ///
    /// Will generate a config.toml with private key that can be used to keep server ticket stable.
    Prepare(PrepareArgs),
}

#[derive(Parser, Debug)]
pub struct CommonArgs {
    /// A custom ALPN to use for the quic endpoint
    ///
    /// This is an expert feature and should only be used if you know what you're doing.
    #[clap(long, default_value = DEFAULT_ALPN)]
    pub custom_alpn: String,

    /// Weather to disable ANSI colors printing, by default colors are printed.
    #[clap(short = 'n', long, action = clap::ArgAction::SetTrue)]
    pub no_colors: bool,

    /// The verbosity level. Repeat to increase verbosity.
    #[clap(short = 'v', long, action = clap::ArgAction::Count)]
    pub verbose: u8,
}

#[derive(Parser, Debug)]
pub struct ListenArgs {
    #[clap(flatten)]
    pub common: CommonArgs,

    /// The host from which to listen, with optional port. Defaults to localhost:8080 (127.0.0.1:8080).
    ///
    /// The host must be a resolvable hostname to which a socket can be bound. e.g 127.0.0.1 or 0.0.0.0
    #[clap(short = 'f', long)]
    pub from: Option<String>,

    /// The server's ticket to connect to. Ticket is printed when you call `serve` command
    pub ticket: String,
}

#[derive(Parser, Debug)]
pub struct ServeArgs {
    #[clap(flatten)]
    pub common: CommonArgs,

    /// The host to which to pass the traffic, e.g localhost:25565
    pub to: String,
}

#[derive(Parser, Debug)]
pub struct PrepareArgs {
    /// The verbosity level. Repeat to increase verbosity.
    #[clap(short = 'v', long, action = clap::ArgAction::Count)]
    pub verbose: u8,
}

#[tokio::main]
async fn main() {
    let args = Args::parse();
    match args.command {
        Commands::Listen(args) => {
            let host = args.from.unwrap_or_else(|| "127.0.0.1:8080".into());
            let Ok(listen_address) = lookup_dns(&host, 8080).map_err(|err| fatal(err));
            let secret = ConfigFile::read().listen_secret();
            listen(
                secret,
                args.common.custom_alpn.as_bytes(),
                args.common.verbose,
                &args.ticket,
                listen_address,
            )
            .await;
        }
        Commands::Serve(args) => {
            let Ok(server_address) = lookup_dns(&args.to, 8080).map_err(|err| fatal(err));
            let config = ConfigFile::read();
            serve(
                config.secret().unwrap_or_else(gen_key),
                args.common.custom_alpn.as_bytes(),
                args.common.verbose,
                server_address,
                config.allow_list(),
            )
            .await;
        }
        Commands::Prepare(args) => {
            let secret = SecretKey::generate(&mut rand::rng());
            let secret_txt = bs58::encode(secret.to_bytes()).into_string();
            if args.verbose > 0 {
                println!("Secret key: {secret_txt}");
            }

            let config = ConfigFile {
                config: Some(ConfigEntry {
                    secret_key: secret_txt,
                    ..Default::default()
                }),
            };
            let toml_file = config.format_template();
            _ = tokio::fs::write(CONFIG_FILE, toml_file)
                .await
                .map_err(|err| fatal(format_args!("Cannot write {CONFIG_FILE} file: {err}")));
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConfigFile {
    config: Option<ConfigEntry>,
}
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConfigEntry {
    secret_key: String,
    listen_secret_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    allow_list: Option<Vec<String>>,
}

impl ConfigFile {
    pub fn read() -> ConfigFile {
        let path = Path::new(CONFIG_FILE);
        if path.exists() {
            let Ok(config) = std::fs::read_to_string(path)
                .map_err(|err| fatal(format_args!("Cannot read {CONFIG_FILE} file: {err}")));
            let config: ConfigFile = match toml::from_str(&config) {
                Ok(config) => config,
                Err(err) => fatal(format_args!("Cannot parse config file: {err}")),
            };
            return config;
        }
        ConfigFile { config: None }
    }

    pub fn format_template(&self) -> String {
        let entry = self.config.as_ref().expect("config cannot be empty");

        TOML_TEMPLATE.replace(PATTERN_SECRET_KEY, &entry.secret_key)
    }

    pub fn secret(&self) -> Option<SecretKey> {
        let key = &self.config.as_ref()?.secret_key;
        let bytes = match bs58::decode(key).into_vec() {
            Ok(bytes) => bytes,
            Err(_) => fatal(format_args!(
                "{CONFIG_FILE}: Cannot decode secret_key, it should be a base58 string"
            )),
        };
        let bytes = match bytes.as_slice().try_into() {
            Ok(bytes) => bytes,
            Err(_) => fatal(format_args!("{CONFIG_FILE}: Invalid secret key length")),
        };
        Some(SecretKey::from_bytes(bytes))
    }
    pub fn listen_secret(&self) -> Option<SecretKey> {
        let config = self.config.as_ref()?;
        let mut key = config.listen_secret_key.as_deref()?;
        if key.trim().is_empty() {
            return None;
        }
        if SECRET_TOML_REFS.contains(&key) {
            key = &config.secret_key;
        }
        let bytes = match bs58::decode(key).into_vec() {
            Ok(bytes) => bytes,
            Err(_) => fatal(format_args!(
                "{CONFIG_FILE}: Cannot decode listen_secret_key, it should be a base58 string"
            )),
        };
        let bytes = match bytes.as_slice().try_into() {
            Ok(bytes) => bytes,
            Err(_) => fatal(format_args!(
                "{CONFIG_FILE}: Invalid listen_secret_key length"
            )),
        };
        Some(SecretKey::from_bytes(bytes))
    }
    pub fn allow_list(&self) -> Option<Vec<EndpointId>> {
        let config = self.config.as_ref()?;
        let list = config.allow_list.as_ref().filter(|list| !list.is_empty())?;
        let list = list.iter().map(|ticket| match decode_ticket(ticket) {
            Some(id) => id,
            None => fatal(format_args!(
                "{CONFIG_FILE}: Invalid allow list ticket: {ticket}"
            )),
        });
        Some(list.collect())
    }
}
fn gen_key() -> SecretKey {
    SecretKey::generate(&mut rand::rng())
}

fn lookup_dns(hostname: &str, default_port: u16) -> Result<SocketAddr, String> {
    let (host, port) = hostname.rsplit_once(':').unwrap_or((hostname, ""));

    let ip_addr = (host, 1234u16)
        .to_socket_addrs()
        .map_err(|err| format!("Cannot read ip address from '{hostname}', err: {err}"))?;

    let mut port_num = default_port;
    if !port.is_empty() {
        port_num = port
            .parse()
            .map_err(|err| format!("Cannot parse port number from '{hostname}', err: {err}"))?;
    }
    let ip_addr = ip_addr
        .map(|addr| addr.ip())
        .find(|ip| ip.is_ipv4())
        .ok_or_else(|| format!("No ip address found for '{hostname}'"))?;
    Ok(SocketAddr::new(ip_addr, port_num))
}

fn fatal(value: impl Display) -> ! {
    eprintln!("Fatal error:\n  {value}\nexiting...");
    std::process::exit(1);
}

async fn serve(
    secret: SecretKey,
    alpn: &[u8],
    verbose: u8,
    server_address: SocketAddr,
    allow_list: Option<Vec<EndpointId>>,
) {
    let allow_list = allow_list.map(Arc::new);
    let address_lookup = RefreshablePkarrPublisher::new(
        PkarrPublisher::n0_dns,
        PkarrResolver::n0_dns().build(),
        secret.clone(),
        Duration::from_secs(30),
        verbose,
    );

    let builder = Endpoint::builder()
        .secret_key(secret.clone())
        .address_lookup(address_lookup)
        .alpns(vec![alpn.to_vec()]);

    let Ok(endpoint) = builder
        .bind()
        .await
        .map_err(|e| fatal(format_args!("Cannot start endpoint: {e}")));
    endpoint.online().await;
    let home_addr = endpoint.addr();
    if verbose > 0 {
        // watch address changes and print to log
        let watch = endpoint.watch_addr();
        let (signal_tx, signal_rx) = oneshot::channel();
        spawn(async move {
            let mut stream = watch.stream();
            let mut first = true;
            let mut signal_tx = Some(signal_tx);
            let mut last_relays = "<unknown>".to_string();
            let mut last_ips = last_relays.clone();
            while let Some(addr) = stream.next().await {
                let relays = addr.addrs.iter().filter_map(|v| match v {
                    TransportAddr::Relay(r) => Some(r),
                    _ => None,
                });
                if let Some(signal_tx) = signal_tx.take() {
                    let _ = signal_tx.send(());
                }
                let relays = relays.collect::<Vec<_>>();
                let relays = if relays.is_empty() {
                    "<empty>".to_string()
                } else {
                    relays
                        .iter()
                        .map(|r| r.to_string())
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                let ips = addr.addrs.iter().filter_map(|v| match v {
                    TransportAddr::Ip(ip) => Some(ip.to_string()),
                    _ => None,
                });
                let ips = ips.collect::<Vec<_>>().join(", ");
                if first {
                    first = false;
                    last_relays = relays.clone();
                    last_ips = ips.clone();
                    println!("Initialized home relay url(s): {relays}");
                    if verbose > 1 {
                        println!("    Home relay ips initialized: {ips}");
                    }
                } else {
                    if last_relays != relays {
                        println!("Updated home relay url(s): {relays}");
                        last_relays = relays.clone();
                    }
                    if verbose > 1 && last_ips != ips {
                        println!("    Home relay ips updated: {ips}");
                        last_ips = ips.clone();
                    }
                }
            }
        });
        let _ = signal_rx.await; // wait for first available address reported
    }

    let to_close = endpoint.clone();
    let (closing_task, _stop_flag) = ClosingTask::new(async move || to_close.close().await);

    spawn(async move {
        while let Some(accepted) = endpoint.accept().await {
            let allow_list = allow_list.clone();
            spawn(async move {
                let accepted = match accepted.await {
                    Ok(accepted) => accepted,
                    Err(e) => {
                        println!("Error accepting connection: {e}, skipping...");
                        return;
                    }
                };
                let id = accepted.remote_id();
                if let Some(allow_list) = &allow_list
                    && !allow_list.contains(&id)
                {
                    if verbose > 0 {
                        println!("Rejected connection from {id}, not in allow list");
                    }
                    return;
                }

                let id = encode_ticket(id);
                if verbose > 0 {
                    println!("Accepted connection from {id}");
                }
                let mut stream_count = 0;
                loop {
                    let (send, recv) = match accepted.accept_bi().await {
                        Ok(stream) => stream,
                        Err(e) => {
                            let result = pin!(accepted.closed())
                                .poll(&mut Context::from_waker(Waker::noop()));
                            if result.is_ready() {
                                if verbose > 0 {
                                    println!("Connection closed by peer, from {id}");
                                }
                                return;
                            } else {
                                println!("Error accepting stream: {e}, dropping connection...");
                                continue;
                            }
                        }
                    };
                    stream_count += 1;
                    if verbose > 1 {
                        println!("Accepted stream {stream_count} from {id}");
                    }
                    let mut src_stream = tokio::io::join(recv, send);
                    let id = id.clone();
                    spawn(async move {
                        //handshake
                        if let Err(e) = handshake(&mut src_stream, Handshake::Tcp(true)).await {
                            println!("Error during handshake: {e}, dropping connection...");
                            return;
                        }
                        if verbose > 1 {
                            println!("Handshake successful, stream {stream_count} from {id}");
                        }

                        let socket_result = match server_address {
                            SocketAddr::V4(_) => TcpSocket::new_v4(),
                            SocketAddr::V6(_) => TcpSocket::new_v6(),
                        };
                        let socket = match socket_result {
                            Ok(socket) => socket,
                            Err(e) => {
                                println!("Error creating socket: {e}, dropping connection...");
                                return;
                            }
                        };
                        let mut dst_stream = match socket.connect(server_address).await {
                            Ok(stream) => stream,
                            Err(e) => {
                                println!(
                                    "Error connecting to {server_address} : {e}, dropping connection..."
                                );
                                return;
                            }
                        };
                        match copy_bidirectional(&mut src_stream, &mut dst_stream).await {
                            Ok((bi, bo)) if verbose > 1 => println!(
                                "Stream {stream_count} closed from {id} ({} in, {} out)",
                                fmt_bytes(bi),
                                fmt_bytes(bo)
                            ),
                            Err(e) => println!("Error copying stream: {e}, dropping connection..."),
                            _ => (),
                        }
                    });
                }
            });
        }
    });

    tokio::task::yield_now().await;

    let ticket = encode_ticket(home_addr.id);

    println!("Passing connections to {server_address}");
    println!("Use this ticket to connect: {ticket}");
    let name = std::env::args().next().unwrap_or(PACKAGE_NAME.to_string());
    println!(
        "    example usage: {name} listen --from localhost:{} {ticket}",
        server_address.port()
    );
    println!("Press ctrl-c to exit");

    closing_task.await.expect("task panic");
    std::process::exit(0);
}

fn fmt_bytes(bytes: u64) -> String {
    let units = ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB"];
    let mut count = bytes as f64;
    let mut unit = 0;
    while count > 1024.0 {
        count /= 1024.0;
        unit += 1;
    }
    match unit {
        0 => format!("{count} {}", units[0]),
        _ => format!("{count:.2} {}", units[unit]),
    }
}

#[derive(Clone)]
pub struct ClosingTask {
    stopped_flag: Arc<AtomicBool>,
}

impl ClosingTask {
    pub fn new<F: Future<Output = ()> + Send + 'static>(
        close_fn: impl FnOnce() -> F + Send + 'static,
    ) -> (JoinHandle<()>, Self) {
        let stopped_flag = Arc::new(AtomicBool::new(false));
        let stopped = stopped_flag.clone();
        let handle = spawn(async move {
            _ = tokio::signal::ctrl_c().await;
            stopped.store(true, Ordering::SeqCst);
            println!(
                "\nPressed ctrl-c, shutting down... (this may take a few seconds, press ctrl-c again to force)"
            );
            tokio::select! {
                _ = tokio::signal::ctrl_c() => {
                    println!("\nPressed ctrl-c again, forced shutdown...");
                    std::process::exit(0);
                }
                _ = close_fn() => std::process::exit(0),
            }
        });
        (handle, Self { stopped_flag })
    }
    pub fn is_stopped(&self) -> bool {
        self.stopped_flag.load(Ordering::SeqCst)
    }
}

async fn listen(
    secret: Option<SecretKey>,
    alpn: &[u8],
    verbose: u8,
    ticket: &str,
    listen_address: SocketAddr,
) {
    let Ok(node_addr) = decode_ticket(ticket)
        .map(EndpointAddr::new)
        .ok_or_else(|| fatal(format_args!("Invalid ticket: {ticket}")));

    let address_lookup = PkarrResolver::n0_dns().build();

    let mut builder = Endpoint::builder().address_lookup(address_lookup);
    if let Some(secret) = secret.clone() {
        builder = builder.secret_key(secret);
    }

    let Ok(endpoint) = builder
        .bind()
        .await
        .map_err(|e| fatal(format_args!("Cannot start endpoint: {e}")));

    let to_close = endpoint.clone();
    let (closing_task, stop_flag) = ClosingTask::new(async move || to_close.close().await);

    let lt = encode_ticket(endpoint.id());
    if verbose > 0 {
        if secret.is_none() {
            println!(
                "info: listener ticket is generated every time, change {CONFIG_FILE} to make it persistent"
            );
        } else {
            println!("info: listener ticket is persistent (configured in {CONFIG_FILE})");
        }
    }
    println!("Your listener ticket is: {lt}");
    println!("    Connecting to {ticket}");
    println!("Press ctrl-c to exit");

    let Ok(conn) = endpoint.connect(node_addr, alpn).await.map_err(|e| {
        if stop_flag.is_stopped() {
            std::process::exit(0)
        }
        fatal(format_args!("Cannot connect to {ticket}: {e}"))
    });
    if verbose > 0 {
        println!("Connected to {ticket}");
    }
    let Ok(listener) = TcpListener::bind(listen_address).await.map_err(|e| {
        if stop_flag.is_stopped() {
            std::process::exit(0)
        }
        fatal(format_args!("Cannot listen on {listen_address}: {e}"))
    });
    if verbose > 0 {
        println!("Listening on {listen_address}");
    }
    while let Ok((mut src_stream, addr)) = listener.accept().await {
        if verbose > 0 {
            println!("Accepted socket connection from {addr}");
        }
        let Ok((send, recv)) = conn.open_bi().await.map_err(|e| {
            if stop_flag.is_stopped() {
                std::process::exit(0)
            }
            fatal(format_args!("Cannot open stream to remote: {e}"))
        });

        let mut dst_stream = tokio::io::join(recv, send);
        //handshake
        if let Err(e) = handshake(&mut dst_stream, Handshake::Tcp(false)).await {
            println!("Error during handshake: {e}, dropping connection...");
            return;
        }
        if verbose > 1 {
            println!("Handshake successful");
        }

        spawn(async move {
            if let Err(e) = copy_bidirectional(&mut dst_stream, &mut src_stream).await {
                println!("Error copying stream: {e}, dropping connection...");
            }
            if verbose > 0 {
                println!("Connection {addr} closed");
            }
        });
    }
    closing_task.abort();
    println!("Listener closed");
    std::process::exit(0);
}

fn encode_ticket(node_id: EndpointId) -> String {
    let id = bs58::encode(node_id.as_bytes()).into_string();
    format!("{TICKET_PREFIX}{id}")
}
fn decode_ticket(ticket: &str) -> Option<EndpointId> {
    let id = ticket.strip_prefix(TICKET_PREFIX)?.as_bytes();
    let bytes = bs58::decode(id).into_vec().ok()?;
    EndpointId::from_bytes(bytes.as_slice().try_into().ok()?).ok()
}

#[derive(Debug, Clone, Copy)]
pub enum Handshake {
    Tcp(bool), // request?
    Udp(bool), // request?
}

async fn handshake<RW: AsyncRead + AsyncWrite + Unpin>(
    stream: &mut RW,
    ty: Handshake,
) -> std::io::Result<()> {
    match ty {
        Handshake::Tcp(true) => {
            let mut buff = [0; HANDSHAKE_TCP_REQUEST.len()];
            stream.read_exact(&mut buff).await?;
            if buff != HANDSHAKE_TCP_REQUEST {
                return Err(std::io::Error::new(
                    ErrorKind::InvalidData,
                    "Invalid handshake request",
                ));
            }
            stream.write_all(HANDSHAKE_TCP_RESPONSE).await?;
            stream.flush().await?;
        }
        Handshake::Tcp(false) => {
            stream.write_all(HANDSHAKE_TCP_REQUEST).await?;
            stream.flush().await?;
            let mut buff = [0; HANDSHAKE_TCP_RESPONSE.len()];
            stream.read_exact(&mut buff).await?;
            if buff != HANDSHAKE_TCP_RESPONSE {
                return Err(std::io::Error::new(
                    ErrorKind::InvalidData,
                    "Invalid handshake response",
                ));
            }
        }
        Handshake::Udp(true) => {
            let mut buff = [0; HANDSHAKE_UDP_REQUEST.len()];
            stream.read_exact(&mut buff).await?;
            if buff != HANDSHAKE_UDP_REQUEST {
                return Err(std::io::Error::new(
                    ErrorKind::InvalidData,
                    "Invalid handshake request",
                ));
            }
            stream.write_all(HANDSHAKE_UDP_RESPONSE).await?;
            stream.flush().await?;
        }
        Handshake::Udp(false) => {
            stream.write_all(HANDSHAKE_UDP_REQUEST).await?;
            stream.flush().await?;
            let mut buff = [0; HANDSHAKE_UDP_RESPONSE.len()];
            stream.read_exact(&mut buff).await?;
            if buff != HANDSHAKE_UDP_RESPONSE {
                return Err(std::io::Error::new(
                    ErrorKind::InvalidData,
                    "Invalid handshake response",
                ));
            }
        }
    }
    Ok(())
}

pub struct RefreshablePkarrPublisher {
    last_data: Arc<Mutex<Option<EndpointData>>>,
    inner: Arc<Mutex<PkarrPublisher>>,
    handle: AbortHandle,
}
impl std::fmt::Debug for RefreshablePkarrPublisher {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RefreshablePkarrPublisher").finish()
    }
}

impl RefreshablePkarrPublisher {
    pub fn new(
        builder: impl Fn() -> PkarrPublisherBuilder + Send + Sync + 'static,
        check_resolver: PkarrResolver,
        secret: SecretKey,
        check_period: Duration,
        verbose: u8,
    ) -> Self {
        let make_builder = Arc::new(builder);
        let builder = make_builder.clone();

        async fn is_resolved(resolver: &PkarrResolver, ticket_pub: EndpointId) -> bool {
            let Some(mut stream) = resolver.resolve(ticket_pub) else {
                return false;
            };
            tokio::time::timeout(Duration::from_secs(30), async move {
                let Some(Ok(item)) = stream.next().await else {
                    return false;
                };

                item.endpoint_id() == ticket_pub
                    && item.endpoint_info().data.relay_urls().count() != 0
            })
            .await
            .unwrap_or(false)
        }
        let inner = Arc::new(Mutex::new(make_builder().build(secret.clone())));
        let last_data = Arc::new(Mutex::new(None));
        let inner_clone = inner.clone();
        let last_data_clone = last_data.clone();
        let task = spawn(async move {
            let ticket_pub = secret.public();
            loop {
                sleep(check_period).await;
                if !is_resolved(&check_resolver, ticket_pub).await {
                    if verbose > 0 {
                        println!("Resolver couldn't find my ticket, refreshing...");
                    }
                    let new_publisher = builder().build(secret.clone());
                    if let Some(data) = last_data_clone.lock().unwrap().as_ref() {
                        new_publisher.publish(data);
                    }
                    *inner_clone.lock().unwrap() = new_publisher;
                }
            }
        });

        Self {
            last_data,
            inner,
            handle: task.abort_handle(),
        }
    }
}
impl Drop for RefreshablePkarrPublisher {
    fn drop(&mut self) {
        self.handle.abort();
    }
}

impl address_lookup::AddressLookup for RefreshablePkarrPublisher {
    fn publish(&self, data: &EndpointData) {
        *self.last_data.lock().unwrap() = Some(data.clone());
        self.inner.lock().unwrap().publish(data);
    }
    fn resolve(
        &self,
        node_id: EndpointId,
    ) -> Option<BoxStream<'static, Result<address_lookup::Item, address_lookup::Error>>> {
        self.inner.lock().unwrap().resolve(node_id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encode_decode_ticket() {
        let id = gen_key().public();
        let ticket = encode_ticket(id);
        let decoded = decode_ticket(&ticket).unwrap();
        assert_eq!(id, decoded);
    }

    #[test]
    fn test_toml_key_ref_not_parsable() {
        for ref_name in SECRET_TOML_REFS {
            let result = decode_ticket(ref_name);
            assert!(result.is_none(), "{ref_name} can be parsed as secret!");
        }
    }

    #[test]
    fn test_parse_template_config() {
        let key = SecretKey::generate(&mut rand::rng());
        let config = ConfigFile {
            config: Some(ConfigEntry {
                secret_key: bs58::encode(key.to_bytes()).into_string(),
                ..Default::default()
            }),
        };
        let template = config.format_template();

        let parsed: ConfigFile = toml::from_str(&template).unwrap();

        assert_eq!(
            config.secret().map(|s| s.to_bytes()),
            parsed.secret().map(|s| s.to_bytes()),
        );
        assert_eq!(
            config.listen_secret().map(|s| s.to_bytes()),
            parsed.listen_secret().map(|s| s.to_bytes())
        );
        assert_eq!(config.allow_list(), parsed.allow_list(),);
    }
}
